# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegename', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelname', models.CharField(max_length=30, unique=True)),
                ('collegename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.College', to_field='collegename')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=20)),
                ('studentrollno', models.CharField(max_length=20)),
                ('studentbldgp', models.CharField(choices=[('1', 'A+'), ('2', 'O+'), ('3', 'B+'), ('4', 'AB+'), ('5', 'A-'), ('6', 'O-'), ('7', 'B-'), ('8', 'AB-')], max_length=3)),
                ('studentroomnoprefix', models.CharField(max_length=3)),
                ('studentroomno', models.CharField(max_length=3)),
                ('collegename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.College', to_field='collegename')),
                ('hostelname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hostel', to_field='hostelname')),
                ('statename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State', to_field='statename')),
            ],
        ),
        migrations.AddField(
            model_name='hostel',
            name='statename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State', to_field='statename'),
        ),
        migrations.AddField(
            model_name='college',
            name='statename',
            field=models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.CASCADE, to='api.State', to_field='statename'),
        ),
    ]
