# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegename', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelname', models.CharField(max_length=30, unique=True)),
                ('collegename', models.ForeignKey(db_column='college', on_delete=django.db.models.deletion.CASCADE, to='api.College', to_field='collegename')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=30)),
                ('studentrollno', models.CharField(max_length=30, unique=True)),
                ('studentemailid', models.CharField(max_length=30, unique=True)),
                ('studentpercentage', models.FloatField(max_length=30)),
                ('studentbloodgp', models.CharField(max_length=5)),
                ('studentyear', models.CharField(max_length=4)),
                ('studentroomno', models.CharField(max_length=5)),
                ('branchname', models.ForeignKey(db_column='branch', on_delete=django.db.models.deletion.CASCADE, to='api.Branch', to_field='branchname')),
                ('collegename', models.ForeignKey(db_column='college', on_delete=django.db.models.deletion.CASCADE, to='api.College', to_field='collegename')),
                ('hostelname', models.ForeignKey(db_column='hostel', on_delete=django.db.models.deletion.CASCADE, to='api.Hostel', to_field='hostelname')),
                ('statename', models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.CASCADE, to='api.State', to_field='statename')),
            ],
        ),
        migrations.AddField(
            model_name='hostel',
            name='statename',
            field=models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.CASCADE, to='api.State', to_field='statename'),
        ),
        migrations.AddField(
            model_name='college',
            name='statename',
            field=models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.CASCADE, to='api.State', to_field='statename'),
        ),
        migrations.AddField(
            model_name='branch',
            name='collegename',
            field=models.ForeignKey(db_column='college', on_delete=django.db.models.deletion.CASCADE, to='api.College', to_field='collegename'),
        ),
        migrations.AddField(
            model_name='branch',
            name='hostelname',
            field=models.ForeignKey(db_column='hostel', on_delete=django.db.models.deletion.CASCADE, to='api.Hostel', to_field='hostelname'),
        ),
        migrations.AddField(
            model_name='branch',
            name='statename',
            field=models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.CASCADE, to='api.State', to_field='statename'),
        ),
    ]
