# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentroomnoprefix',
            field=models.CharField(default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='studentbldgp',
            field=models.CharField(choices=[('1', 'A+'), ('2', 'O+'), ('3', 'B+'), ('4', 'AB+'), ('5', 'A-'), ('6', 'O-'), ('7', 'B-'), ('8', 'AB-')], max_length=3),
        ),
    ]
