# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tempvar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentrollno',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentyear',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
