# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170327_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentroomno',
            field=models.CharField(max_length=20),
        ),
    ]
