# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170322_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='statename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State', to_field='statename'),
        ),
        migrations.AlterField(
            model_name='state',
            name='statename',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
