# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170322_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='collegename',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.College', to_field='collegename'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostelname',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State', to_field='statename'),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.College', to_field='collegename'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostelname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hostel', to_field='hostelname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State', to_field='statename'),
        ),
    ]
