# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170322_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='hostelname',
            new_name='hostel',
        ),
    ]
