# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_candonateblood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentroomno',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentyear',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
