# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170322_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='college',
            new_name='collegename',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='hostel',
            new_name='hostelname',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='state',
            new_name='statename',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='college',
            new_name='collegename',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='state',
            new_name='statename',
        ),
    ]
