# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentchoice1', models.CharField(default=None, max_length=30)),
                ('studentchoice2', models.CharField(default=None, max_length=30)),
                ('studentchoice3', models.CharField(default=None, max_length=30)),
                ('studentchoice4', models.CharField(default=None, max_length=30)),
                ('studentchoice5', models.CharField(default=None, max_length=30)),
                ('studentchoice6', models.CharField(default=None, max_length=30)),
                ('studentchoice7', models.CharField(default=None, max_length=30)),
                ('studentchoice8', models.CharField(default=None, max_length=30)),
                ('studentchoice9', models.CharField(default=None, max_length=30)),
                ('studentchoice10', models.CharField(default=None, max_length=30)),
                ('roomallocated', models.CharField(default='NULL', max_length=30)),
                ('studentrollno', models.ForeignKey(db_column='Roll No', on_delete=django.db.models.deletion.CASCADE, to='api.Student', to_field='studentrollno', unique=True)),
            ],
        ),
    ]
