# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelallocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelallocation',
            name='studentrollno',
            field=models.OneToOneField(db_column='Roll No', on_delete=django.db.models.deletion.CASCADE, to='api.Student', to_field='studentrollno'),
        ),
    ]
