# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('hostelallocation', '0002_auto_20170405_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalAllocatedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomallocated', models.CharField(default='NULL', max_length=30)),
                ('studentrollno', models.OneToOneField(db_column='Roll No', on_delete=django.db.models.deletion.CASCADE, to='api.Student', to_field='studentrollno')),
            ],
        ),
        migrations.RemoveField(
            model_name='hostelallocation',
            name='roomallocated',
        ),
    ]
