# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelallocation', '0004_auto_20170415_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalallocatedlist',
            name='studentrollno',
            field=models.ForeignKey(db_column='Roll No', on_delete=django.db.models.deletion.CASCADE, to='api.Student', to_field='studentrollno', unique=True),
        ),
    ]
