# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelallocation', '0005_auto_20170416_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalallocatedlist',
            name='studentrollno',
            field=models.CharField(db_column='Roll No', max_length=30, unique=True),
        ),
    ]
