# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('fillinginfostatus', models.CharField(max_length=32)),
            ],
        ),
    ]
