# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_postlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlogin',
            name='fillinginfostatus',
        ),
    ]
