# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_remove_postlogin_fillinginfostatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('url', models.URLField(default='http://hmsonline.herokuapp.com')),
                ('text', models.TextField(default='Notice is Empty')),
            ],
        ),
    ]
