# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_notices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='title',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
